(function() {var implementors = {};
implementors["node_archive"] = [{text:"impl Fail for <a class=\"struct\" href=\"node_archive/tarball/struct.MissingHeaderError.html\" title=\"struct node_archive::tarball::MissingHeaderError\">MissingHeaderError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"node_archive/tarball/struct.UnexpectedContentLengthError.html\" title=\"struct node_archive::tarball::UnexpectedContentLengthError\">UnexpectedContentLengthError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"node_archive/tarball/struct.ByteRangesNotAcceptedError.html\" title=\"struct node_archive::tarball::ByteRangesNotAcceptedError\">ByteRangesNotAcceptedError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"node_archive/struct.HttpError.html\" title=\"struct node_archive::HttpError\">HttpError</a>",synthetic:false,types:[]},];
implementors["notion"] = [{text:"impl Fail for <a class=\"struct\" href=\"notion/error/struct.CliParseError.html\" title=\"struct notion::error::CliParseError\">CliParseError</a>",synthetic:false,types:[]},];
implementors["notion_core"] = [{text:"impl Fail for <a class=\"struct\" href=\"notion_core/catalog/struct.NoNodeVersionFoundError.html\" title=\"struct notion_core::catalog::NoNodeVersionFoundError\">NoNodeVersionFoundError</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/path/unix/struct.NoHomeEnvVar.html\" title=\"struct notion_core::path::unix::NoHomeEnvVar\">NoHomeEnvVar</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/plugin/struct.InvalidCommandError.html\" title=\"struct notion_core::plugin::InvalidCommandError\">InvalidCommandError</a>",synthetic:false,types:["notion_core::plugin::InvalidCommandError"]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/serial/plugin/struct.BothUrlAndBin.html\" title=\"struct notion_core::serial::plugin::BothUrlAndBin\">BothUrlAndBin</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/serial/plugin/struct.NeitherUrlNorBin.html\" title=\"struct notion_core::serial::plugin::NeitherUrlNorBin\">NeitherUrlNorBin</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/serial/plugin/struct.BothUrlAndStream.html\" title=\"struct notion_core::serial::plugin::BothUrlAndStream\">BothUrlAndStream</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/serial/plugin/struct.NeitherUrlNorStream.html\" title=\"struct notion_core::serial::plugin::NeitherUrlNorStream\">NeitherUrlNorStream</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/serial/plugin/struct.FalseStream.html\" title=\"struct notion_core::serial::plugin::FalseStream\">FalseStream</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/tool/struct.NoArg0Error.html\" title=\"struct notion_core::tool::NoArg0Error\">NoArg0Error</a>",synthetic:false,types:[]},{text:"impl Fail for <a class=\"struct\" href=\"notion_core/tool/struct.NoGlobalError.html\" title=\"struct notion_core::tool::NoGlobalError\">NoGlobalError</a>",synthetic:false,types:[]},];
implementors["notion_fail"] = [{text:"impl Fail for <a class=\"struct\" href=\"notion_fail/struct.NotionError.html\" title=\"struct notion_fail::NotionError\">NotionError</a>",synthetic:false,types:["notion_fail::NotionError"]},{text:"impl Fail for <a class=\"struct\" href=\"notion_fail/struct.UnknownNotionError.html\" title=\"struct notion_fail::UnknownNotionError\">UnknownNotionError</a>",synthetic:false,types:[]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
